name: Demo Workflow
on: workflow_dispatch
jobs: 
  print: 
    runs-on: ubuntu-latest  
    steps:
      - name: Print to console
        run: echo Hello Github Action!
      - name: Print a few lines 
        run: |
          echo First line!
          echo Second line!
